services:
  postgres:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: ead-course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco123
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"